"""Supabase Storage Manager for App 3 Content Outputs.

Handles storing and managing content files generated by App 3's content generators
in Supabase Storage buckets. Each content type has its own storage path and metadata.
"""

from typing import Dict, Optional
from datetime import datetime
import os
from supabase import create_client, Client

class SupabaseStorageManager:
    """Manages storage of content files in Supabase buckets."""
    
    _instance = None
    
    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(SupabaseStorageManager, cls).__new__(cls)
        return cls._instance
    
    def __init__(self):
        """Initialize Supabase client and storage settings."""
        if not hasattr(self, 'initialized'):
            self.supabase_url = os.getenv("SUPABASE_URL")
            self.supabase_key = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
            self.client: Optional[Client] = None
            self.bucket_name = "content"  # Using same bucket as input
            
            # Content type to storage path mapping
            self.content_paths = {
                "website": "published_content/website",
                "blog": "published_content/blog",
                "social": "published_content/social",
                "bio": "published_content/bio",
                "ad": "published_content/ad-copy",
                "show_notes": "published_content/show-notes",
                "reputation": "published_content/reputation"
            }
            self.initialized = True
    
    def initialize(self) -> None:
        """Initialize Supabase client."""
        if not self.supabase_url or not self.supabase_key:
            raise ValueError("Supabase URL and key must be set in environment variables")
            
        self.client = create_client(self.supabase_url, self.supabase_key)
    
    def store_content(self, content_type: str, content: str, metadata: Dict) -> str:
        """Store content in Supabase with metadata.
        
        Args:
            content_type: Type of content (website, blog, etc.)
            content: The content to store
            metadata: Additional metadata about the content
            
        Returns:
            Storage path where content was stored
        """
        if not self.client:
            self.initialize()
            
        if content_type not in self.content_paths:
            raise ValueError(f"Invalid content type: {content_type}")
            
        # Generate filename
        client_id = metadata.get('client_id', 'unknown')
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{client_id}_{content_type}_{timestamp}.html"
            
        # Construct storage path
        storage_path = f"{self.content_paths[content_type]}/{filename}"
        
        # Store content
        self.client.storage.from_(self.bucket_name).upload(
            path=storage_path,
            file=content.encode(),
            file_options={"content-type": "text/html"}
        )
        
        # Store metadata in content table
        self.client.table('content').insert({
            'path': storage_path,
            'client_id': client_id,
            'content_type': content_type,
            'metadata': metadata,
            'created_at': datetime.now().isoformat()
        }).execute()
        
        return storage_path

# Create singleton instance
storage_manager = SupabaseStorageManager()
