"""Supabase client for App 3 markdown content management.

Handles database operations for storing markdown content generated by App 3
in the Supabase content table.
"""

import os
from typing import Optional
from supabase import create_client, Client
from dotenv import load_dotenv

class SupabaseClient:
    """Manages Supabase database operations for markdown content."""
    
    def __init__(self):
        """Initialize Supabase client using environment variables."""
        load_dotenv()  # Load environment variables
        
        self.supabase_url = os.getenv("SUPABASE_URL")
        self.service_role_key = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
        self.client: Optional[Client] = None
        
    def initialize(self) -> None:
        """Initialize Supabase client and verify content table exists."""
        if not self.supabase_url or not self.service_role_key:
            raise ValueError(
                "SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set in environment variables"
            )
            
        # Create Supabase client
        self.client = create_client(self.supabase_url, self.service_role_key)
        
        # Verify content table exists
        try:
            self.client.table('content').select('id', count='exact').execute()
            print("Successfully connected to Supabase content table")
        except Exception as e:
            raise RuntimeError(
                f"Failed to verify content table exists: {str(e)}\n"
                "Please ensure the content table is created in your Supabase database"
            )
    
    def get_client(self) -> Client:
        """Get initialized Supabase client."""
        if not self.client:
            self.initialize()
        return self.client

# Create singleton instance
supabase = SupabaseClient()
