import { writeContent } from '../../utils/contentWriter.ts';

interface StyleProfile {
  voice: string[];
  themes: string[];
}

export async function generateInstagramPost(transcript: string, styleProfile: StyleProfile) {
  // Extract key insights from the transcript chunks
  const chunks = transcript.split('## [Chunk').slice(1);
  const insights = chunks.map(chunk => {
    const quote = chunk.match(/> Speaker \d+: (.+?)(?=\n|$)/)?.[1] || '';
    return quote.trim();
  }).filter(Boolean);

  // Create an engaging Instagram post
  const mainQuote = insights[0]; // Use the first insight as the main quote
  const callToAction = insights[2]; // Use the third insight for call to action

  const instagramContent = `# Your Authentic Journey Begins Here 

"${mainQuote}"

Three steps to finding your authentic path:
 Trust your inner compass
 Embrace what makes you different
 Take inspired action

Remember: ${callToAction}

Double tap if this resonates! 
Share your journey in the comments 

...

#AuthenticSelf #PersonalGrowth #LeadershipJourney #FindingYourPath #Authenticity #SelfDiscovery #PersonalDevelopment #Motivation #Inspiration`;

  await writeContent('output_instagram.md', instagramContent, {
    section: 'instagram',
    title: "Your Authentic Leadership Journey: Visual Guide",
    platform: 'instagram',
    caption: 'Carousel post on authentic leadership',
    scheduledDate: new Date().toISOString(),
    status: 'draft',
    tags: ['leadership', 'authenticity', 'carousel'],
    thumbnail: 'authentic-path-visual.jpg' // Would be generated by image generator
  });

  return instagramContent;
}
